### ISSUE TITLE
Incorrect checksum error when it's not a bandwidth cap. 

### ISSUE THREAD

**Issue by coniferous1** [SpaceinvaderOne/RetroNASinabox#1]
Hi! I noticed I was getting an error in the docker container when it is downloading the image. 

"Downloaded file has an incorrect checksum. Trying next link..."

But when visiting the page manually and downloading the file it worked. I unzipped retronas.zip to /mnt/user/domains/RetroNAS/vdisk1.img "defaults" and then the installer kicked off. Is it possible that the checksum validation is not working properly?

Running on :latest docker container.

**Comment by coniferous1** [comment]
I just noticed "Also, if a checksum fails, it does not necessarily mean that the image has been tampered with. It could be due to a failed link or corruption during the download. The MD5 check just makes sure the vDisk you get is correct."

I can't read! Thank you for your work.

**Comment by stayupthetree** [comment]
encountering same issue, thanks for the work around
