### ISSUE TITLE
Can't continue with setup

### ISSUE THREAD

**Issue by FreakyBigFoot** [SpaceinvaderOne/RetroNASinabox#5]
I ran the docker and it created the VM. But when I VNC into the VM and run 'retronas' I get this:

```
Item not changed
Press [Enter] to continue...
```

Can't seem to actually move forward on the setup.

**Comment by FreakyBigFoot** [comment]
Oh do I need to actually create the 'pi' user or something?

**Comment by Northwave** [comment]
folow the manual - it needs to be changed to retronas
https://github.com/SpaceinvaderOne/RetroNASinabox?tab=readme-ov-file
